### ISSUE TITLE
PowerDNS Recursor RPZ with cacheable results, high latency?

### ISSUE THREAD

**Issue by 24fpsDaVinci** [hlindqvist/hlindqvist.github.io#1]
I tested "rpz with cacheable results" and I'm experiencing latency compared to default pdns recursor config with no rpz, is this normal?

**Comment by hlindqvist** [comment]
> I tested "rpz with cacheable results" and I'm experiencing latency compared to default pdns recursor config with no rpz, is this normal?

I suppose some increase in latency is expected from RPZ processing, but I wouldn't expect too much. However, startup will be notably slower if you have many/big RPZ zones.

What kind of results are you seeing?

**Comment by 24fpsDaVinci** [comment]
after more testing, i switched to using the config described [here](https://doc.powerdns.com/recursor/lua-config/rpz.html#configuring-rpz)
` rpzFile("dblfilename", {defpol=Policy.Custom, defcontent="badserver.example.com"})`

The defcontent tag also triggers caching but without any lua scripting involved.
This method seems to have lower latency for me, i didnt do any formal testing so I cant say for sure. I'm using oisd full rpz file.

**Comment by 24fpsDaVinci** [comment]
this tag also helps with loading times.
https://doc.powerdns.com/recursor/lua-config/rpz.html#zonesizehint
`An indication of the number of expected entries in the zone, speeding up the loading of huge zones by reserving space in advance.`
